TENDER_SWITCHED = "tender_switched"
TENDER_NOT_SWITCHED = "tender_not_switched"
TENDER_ALREADY_IN_PROCESS = "tender_already_in_process"
TENDER_EXCEPTION = "tender_exception"
MONGODB_EXCEPTION = "c_mongodb_exception"
PROFILE_TO_SYNC = "profile_to_sync"
PROFILE_EXISTS = "profile_exists"
DATABRIDGE_SKIP_TENDER = "skip_tender"
